# Generated by Django 4.1.5 on 2023-01-15 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wisher', models.CharField(max_length=100)),
                ('wishContent', models.CharField(max_length=1000)),
                ('reward', models.CharField(max_length=1000)),
            ],
        ),
    ]
