# Generated by Django 4.1.5 on 2023-01-15 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='isRealized',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
